[build]
  command = 'make build'
  publish = 'public'
  base = './'
  #functions = "./functions"

[build.environment]
HUGO_VERSION="0.68.3"
HUGO_ENV="production"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"