name: Trigger Netlify Build

on:
  schedule:
    # every day at 00.01AM
    - cron: '1 0 * * *'

jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.netlifyBuildUrl }}
